[main]
# The default PPD profile
default = balanced
battery_detection = false
sysfs_acpi_monitor = true

[profiles]
# PPD = TuneD
power-saver = powersave-tweaked
balanced = balanced-tweaked
performance = throughput-performance-tweaked

[battery]
# PPD = TuneD
balanced = balanced-battery-tweaked
